version: '3'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SubHuntMaster
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/SubHuntMaster?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:

  spring-app-angular:
    build:
      context: ./SubHuntHaster_fr
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - spring-app